#!/bin/sh
#
# options:
#  --url url        the full URL to download. may include login/password
#  --filename file  filename, starting with /
#  --md5 sum        md5 sum, if specified by the user

while $(echo $1 | grep -q '^--') ; do
  case "$1" in
    --url) url=$2; shift ; shift ;;
    --filename) fn=$2; shift ; shift ;;
    --md5) md5=$2; shift ; shift ;;
    *) echo unknown option $1 ; exit 1 ;;
  esac
done

[ -n "$url" ] || { echo URL not specified; exit 1; }
[ -n "$fn" ] || { echo Filename not specified; exit 1; }

md5() {
    [ -n "$md5" -a -f "$fn" ] && \
    [ "$md5" != "$(md5sum $fn | cut -c-32)" ] && \
    rm -f $fn ; \
    /bin/true
}

# check whether the cached copy is up to date (if there is a cached copy)
md5

# try to download, three times, at intervals
[ -e "$fn" ] || ( wget -O $fn $url ; md5 )
[ -e "$fn" ] || ( sleep 5 ; wget -O $fn $url ; md5 )
[ -e "$fn" ] || ( sleep 15 ; wget -O $fn $url ; md5 )
