#!/bin/sh
#
# options (all are supplied):
#  --uid number     the uid that is to own all files
#  --gid number     the uid that is to own all files
#  --filename path  the file that is to be unpacked (/foo/bar.zip)
#                   note that it may be a .tar.gz, .jar, .zip or
#                   whatever. your choice.
#  --root path      the base directory where to unpack

while $(echo $1 | grep -q '^--') ; do
  case "$1" in
    --gid) gid=$2; shift ; shift ;;
    --uid) uid=$2; shift ; shift ;;
    --root) root=$2; shift ; shift ;;
    --filename) fn=$2; shift ; shift ;;
    *) echo unknown option $1 ; exit 1 ;;
  esac
done

[ -n "$gid" ] || { echo GID not specified; exit 1; }
[ -n "$url" ] || { echo UID not specified; exit 1; }
[ -n "$root" ] || { echo Destination directory not specified; exit 1; }
[ -n "$fn" ] || { echo Filename not specified; exit 1; }


mkdir -p $root/tmp
cd $root
case $fn in
  *.zip) unzip $fn ;;
  *.tar.gz) tar zxf $fn ;;
  *.jar) cp $fn . ;;
  *) echo Unknown file type $fn ; exit 1 ;;
esac

chown -R $uid:$gid $work
