#!/bin/sh

# this needs to be included in the other scripts from this directory:
#    . $(dirname $0)/pathsetup

# PAYLOADDIR is the base directory where nodee will untar payload tarballs
PAYLOADDIR=/tmp/sw/virgin

# WORKDIR is the base directory in which nodee will create scratch directories
WORKDIR=/tmp/sw/work

# Each WORKDIR subdirectory serves a single process and will contain
# three directories, scratch, tmp and shadow. Nodee will keep scratch
# around as long as the process is running, and may keep it for a
# little while after that. Files in /tmp may be deleted by Nodee at
# any time, but in general it tries to avoid deleting recent files,
# and in practice it hasn't deleted a single file yet. shadow is a
# mirror of the directory containing the executables.
